-- ============================================================
-- Internal SQLite schema for query-optimizer.
-- GENERATED by `npm run db:build` from src/lib/db/schema/tables.ts.
-- Do not edit by hand — edit the table specs and rebuild.
-- ============================================================

PRAGMA foreign_keys = ON;

-- Application users.
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  first_name TEXT,
  last_name TEXT,
  email TEXT NOT NULL UNIQUE,
  password TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('pending', 'active', 'rejected', 'deleted')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER IF NOT EXISTS trg_users_updated_at
AFTER UPDATE ON users
FOR EACH ROW
BEGIN
  UPDATE users SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Named roles with a permissions set (JSON).
CREATE TABLE IF NOT EXISTS roles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  permissions JSON CHECK (permissions IS NULL OR json_valid(permissions))
);

-- App-level key/value settings (admin-configurable).
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT NOT NULL UNIQUE,
  value JSON CHECK (value IS NULL OR json_valid(value)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER IF NOT EXISTS trg_settings_updated_at
AFTER UPDATE ON settings
FOR EACH ROW
BEGIN
  UPDATE settings SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- A company / team / client / project.
CREATE TABLE IF NOT EXISTS workspaces (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER IF NOT EXISTS trg_workspaces_updated_at
AFTER UPDATE ON workspaces
FOR EACH ROW
BEGIN
  UPDATE workspaces SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Per-workspace user authorization (which users may access a workspace + role).
CREATE TABLE IF NOT EXISTS workspace_members (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, user_id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_workspace_members_workspace_id ON workspace_members (workspace_id);
CREATE INDEX IF NOT EXISTS ix_workspace_members_user_id ON workspace_members (user_id);
CREATE TRIGGER IF NOT EXISTS trg_workspace_members_updated_at
AFTER UPDATE ON workspace_members
FOR EACH ROW
BEGIN
  UPDATE workspace_members SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Assigns a role to a user, with optional per-assignment overrides.
CREATE TABLE IF NOT EXISTS user_roles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  custom_permissions JSON CHECK (custom_permissions IS NULL OR json_valid(custom_permissions)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_user_roles_user_id ON user_roles (user_id);
CREATE TRIGGER IF NOT EXISTS trg_user_roles_updated_at
AFTER UPDATE ON user_roles
FOR EACH ROW
BEGIN
  UPDATE user_roles SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Customer database connections (consumed by the mysql-runner).
CREATE TABLE IF NOT EXISTS databases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  engine TEXT NOT NULL DEFAULT 'mysql' CHECK (engine IN ('mysql', 'mariadb')),
  host TEXT NOT NULL,
  port INTEGER NOT NULL DEFAULT 3306,
  username TEXT NOT NULL,
  password_enc TEXT,
  db_name TEXT,
  ssl_mode TEXT NOT NULL DEFAULT 'disabled' CHECK (ssl_mode IN ('disabled', 'require', 'require_no_verify')),
  connection_method TEXT NOT NULL DEFAULT 'direct' CHECK (connection_method IN ('direct', 'ssh')),
  ssh_host TEXT,
  ssh_port INTEGER DEFAULT 22,
  ssh_username TEXT,
  ssh_auth_method TEXT CHECK (ssh_auth_method IN ('password', 'privateKey')),
  ssh_password_enc TEXT,
  ssh_private_key_enc TEXT,
  ssh_passphrase_enc TEXT,
  last_sync_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, name),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_databases_workspace_id ON databases (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_databases_updated_at
AFTER UPDATE ON databases
FOR EACH ROW
BEGIN
  UPDATE databases SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Synced table metadata for a database (no customer data).
CREATE TABLE IF NOT EXISTS db_tables (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  database_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  engine TEXT,
  row_count INTEGER DEFAULT 0,
  size_bytes INTEGER DEFAULT 0,
  index_count INTEGER DEFAULT 0,
  description TEXT,
  last_sync_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (database_id, name),
  FOREIGN KEY (database_id) REFERENCES databases(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_db_tables_database_id ON db_tables (database_id);
CREATE TRIGGER IF NOT EXISTS trg_db_tables_updated_at
AFTER UPDATE ON db_tables
FOR EACH ROW
BEGIN
  UPDATE db_tables SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Synced column metadata for a table.
CREATE TABLE IF NOT EXISTS db_columns (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  db_table_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  data_type TEXT,
  is_nullable INTEGER DEFAULT 1 CHECK (is_nullable IN (0, 1)),
  is_primary_key INTEGER DEFAULT 0 CHECK (is_primary_key IN (0, 1)),
  is_indexed INTEGER DEFAULT 0 CHECK (is_indexed IN (0, 1)),
  ordinal INTEGER,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (db_table_id, name),
  FOREIGN KEY (db_table_id) REFERENCES db_tables(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_db_columns_db_table_id ON db_columns (db_table_id);
CREATE TRIGGER IF NOT EXISTS trg_db_columns_updated_at
AFTER UPDATE ON db_columns
FOR EACH ROW
BEGIN
  UPDATE db_columns SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Business context for the AI, scoped at several levels.
CREATE TABLE IF NOT EXISTS instructions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  scope TEXT NOT NULL CHECK (scope IN ('workspace', 'database', 'table', 'column')),
  database_id INTEGER,
  db_table_id INTEGER,
  target_column TEXT,
  content TEXT NOT NULL,
  created_by INTEGER,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (database_id) REFERENCES databases(id) ON DELETE SET NULL,
  FOREIGN KEY (db_table_id) REFERENCES db_tables(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_instructions_workspace_id ON instructions (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_instructions_updated_at
AFTER UPDATE ON instructions
FOR EACH ROW
BEGIN
  UPDATE instructions SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Encrypted API keys / secrets (e.g. AI provider keys).
CREATE TABLE IF NOT EXISTS env_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  provider TEXT CHECK (provider IN ('openai', 'claude', 'gemini', 'openrouter', 'other')),
  key_enc TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, name),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_env_keys_workspace_id ON env_keys (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_env_keys_updated_at
AFTER UPDATE ON env_keys
FOR EACH ROW
BEGIN
  UPDATE env_keys SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Configured AI agents (provider + model + prompt).
CREATE TABLE IF NOT EXISTS agents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('openai', 'claude', 'gemini', 'openrouter')),
  model TEXT,
  env_key_id INTEGER,
  system_prompt TEXT,
  config JSON CHECK (config IS NULL OR json_valid(config)),
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, name),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (env_key_id) REFERENCES env_keys(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_agents_workspace_id ON agents (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_agents_updated_at
AFTER UPDATE ON agents
FOR EACH ROW
BEGIN
  UPDATE agents SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- A conversation thread.
CREATE TABLE IF NOT EXISTS chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  user_id INTEGER,
  database_id INTEGER,
  title TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (database_id) REFERENCES databases(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_chat_workspace_id ON chat (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_chat_updated_at
AFTER UPDATE ON chat
FOR EACH ROW
BEGIN
  UPDATE chat SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Messages within a chat, with any generated SQL.
CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  chat_id INTEGER NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  generated_sql TEXT,
  metadata JSON CHECK (metadata IS NULL OR json_valid(metadata)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chat_id) REFERENCES chat(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_chat_messages_chat_id ON chat_messages (chat_id);

-- User suggestions (add index, improve instruction, ...).
CREATE TABLE IF NOT EXISTS suggestions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  user_id INTEGER,
  database_id INTEGER,
  type TEXT NOT NULL CHECK (type IN ('add_index', 'improve_instruction', 'create_relation', 'rename_column', 'other')),
  title TEXT NOT NULL,
  body TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'implemented')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (database_id) REFERENCES databases(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_suggestions_workspace_id ON suggestions (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_suggestions_updated_at
AFTER UPDATE ON suggestions
FOR EACH ROW
BEGIN
  UPDATE suggestions SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Generic key/value metadata attached to any entity.
CREATE TABLE IF NOT EXISTS metadata (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER,
  entity_type TEXT NOT NULL,
  entity_id INTEGER,
  key TEXT NOT NULL,
  value JSON CHECK (value IS NULL OR json_valid(value)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (entity_type, entity_id, key),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_metadata_workspace_id ON metadata (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_metadata_updated_at
AFTER UPDATE ON metadata
FOR EACH ROW
BEGIN
  UPDATE metadata SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Query-safety rules: allow/block statement types per workspace/db.
CREATE TABLE IF NOT EXISTS query_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER NOT NULL,
  database_id INTEGER,
  statement_type TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('allow', 'block')),
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, database_id, statement_type),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
  FOREIGN KEY (database_id) REFERENCES databases(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_query_rules_workspace_id ON query_rules (workspace_id);
CREATE TRIGGER IF NOT EXISTS trg_query_rules_updated_at
AFTER UPDATE ON query_rules
FOR EACH ROW
BEGIN
  UPDATE query_rules SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

-- Append-only audit of user actions.
CREATE TABLE IF NOT EXISTS user_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id INTEGER,
  user_id INTEGER,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  ip_address TEXT,
  metadata JSON CHECK (metadata IS NULL OR json_valid(metadata)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_user_logs_workspace_id ON user_logs (workspace_id);
CREATE INDEX IF NOT EXISTS ix_user_logs_user_id ON user_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_user_logs_created_at ON user_logs (created_at);

-- Append-only system events / errors.
CREATE TABLE IF NOT EXISTS system_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  level TEXT NOT NULL DEFAULT 'info' CHECK (level IN ('debug', 'info', 'warn', 'error')),
  source TEXT,
  message TEXT NOT NULL,
  metadata JSON CHECK (metadata IS NULL OR json_valid(metadata)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_system_logs_level ON system_logs (level);
CREATE INDEX IF NOT EXISTS ix_system_logs_created_at ON system_logs (created_at);
